### ISSUE TITLE
It would be nice to have tests for the lib

### ISSUE THREAD

**Issue by jackrwright** [canopas/UIPilot#17]
Any thoughts on how to add meaningful tests for the lib?

**Comment by jimmy0251** [comment]
Hi @jackrwright Hope you are doing well.

Any luck on updating tests to use public APIs? Let me know if you think you will not have time to do it. I'm planning to add some tests as well, in that case we should close the PR.

**Comment by jimmy0251** [comment]
Thanks a lot!
