### ISSUE TITLE
Push fresh version to CocoaPods Specs

### ISSUE THREAD

**Issue by igooor-bb** [canopas/UIPilot#33]
Hello, I wanted to install the latest version of UIPilot through CocoaPods and found that the latest version in Specs is 1.3.1
It turns out that [the related text in the README.md](https://github.com/canopas/UIPilot#cocoapods) is not relevant yet, so I think it is worth raising the version in Specs via trunk.

**Comment by igooor-bb** [comment]
Btw in case any of readers need to install it right now through CocoaPods, I did it using the following syntax:

```ruby
pod 'UIPilot', :git => 'https://github.com/canopas/UIPilot.git', :tag => '2.0.1'
```

**Comment by jimmy0251** [comment]
Pushed version 2.0.2 on cocoapods.
