### ISSUE TITLE
Manual `pop()` causes two routes to be deleted from the stack at once

### ISSUE THREAD

**Issue by igooor-bb** [canopas/UIPilot#34]
I noticed that manually calling the `pop()` method causes two routes to be removed from the stack at once.

This is because manually calling this method causes the controller to close via `popToViewController()`, which in turn triggers a call to `onSystemPop()` due to an event from the `PopAwareUINavigationController`.

So, the controller is closed once, but the values are removed from the `_routes` stack twice. Then this leads to problems with navigation, because stacks are no longer synchronized with each other.

**Comment by jimmy0251** [comment]
This is fixed with version 2.0.2. `PopAwareUINavigationController` will now check size of stack before making pop call.

**Comment by igooor-bb** [comment]
Checked it out, this solution seems more convenient. Then I will close the issue and PR. Thank you!
