### ISSUE TITLE
Is UIPilot working with TabView?

### ISSUE THREAD

**Issue by mrtrinh5293** [canopas/UIPilot#39]
Hi team,
I've been trying a few ways to achieve my goal. Which is is implement UIPilot for my complex app.
Currently, I have a MainTabview, it is the "middleware view" for me to navigate to different Views
For example:

       TabView(selection: $tabVM.tabSelection) {
       Tab1View()
          .tag("tab1")

       Tab2View()
          .tag("tab2")
       ...
       }

Each tab view has different duties and they are the root view for many other views. For example:
Tab1View -> Tab1DetailView -> WorksheetView -> ResultView -> CompleteView 
...

My goal is to navigate from CompleteView -> Tab1. I've tried to create a new view (NewTab1View) to replace the Tab1View from MainTabView:

       enum EducationAppRoute: Equatable {
           case Tab1View
           case CompleteView
       }
       struct NewTab1View: View {
           @StateObject var pilot = UIPilot(initial: Tab1.Tab1View)
    
           var body: some View {
               UIPilotHost(pilot)  { route in
                   switch route {
                   case .Tab1View: Tab1View()
                   case .CompleteView: CompleteView()
       ...
and, within the CompleteView, I have 

       Button {
            pilot.popTo(.NewTab1View)
       } label: {
            ...
       }

However, this does not work, the button action does take me back to MainTab1VIew()
I have not change anything much ( NavigationView { ... }, NavigationLink between views ).

**Comment by mrtrinh5293** [comment]
Also, I cant not install version 2.0.2
"None of your spec sources contain a spec satisfying the dependency: `UIPilot (~> 2.0.2)`."

**Comment by iosYash** [comment]
You have to simply write
